enum FilterActionType {
    GET_FILTER_PRODUCT = "GET_FILTER_PRODUCT",
    GET_SEARCHED_PRODUCT = 'GET_SEARCHED_PRODUCT',
    GET_PRODUCT_STAR = 'GET_PRODUCT_STAR',
    GET_PRODUCT_PRICE = 'GET_PRODUCT_PRICE'
}

export { FilterActionType }